
services:
    main:
        container_name: nabu-php-main
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "3000:80"
        volumes:
            - ./demonstration:/var/www/html/public
            - ./src:/var/www/html/src
        tty: true
        #command: [""]